version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - export CLEANED_BRANCH=$(echo $CODEBUILD_WEBHOOK_TRIGGER | sed 's/branch\///' | sed 's/pr\///')
  build:
    commands:
      - cd glue
      - echo $CODEBUILD_WEBHOOK_TRIGGER
      - echo $CLEANED_BRANCH
